"""S7 / D1: assemble the agent-facing skill doc *from the running code*.

The headline guarantee is drift-proofing. Two parts of the rendered document
are load-bearing and are derived from the live package, never hand-maintained:

1. **Version stamp** — read from ``browserwright.__version__`` so the reader
   knows exactly which installed build these instructions describe.
2. **Primitive surface** — enumerated by walking ``browserwright.EXPORTS`` at
   runtime and introspecting each callable for its signature + first docstring
   line. Add or remove a primitive in ``api.py`` and the doc follows
   automatically; it can never silently disagree with the binary.

The curated prose (the "how to think about this tool" guidance) is optional and
is read at runtime from a real ``SKILL.md`` if one is present; otherwise the
CLI ``HELP`` banner is used as the curated header. We never embed a frozen copy
of that prose here — only the generated, version-locked sections are
authoritative.
"""
from __future__ import annotations

import inspect
from pathlib import Path

import browserwright


def _version() -> str:
    """Installed package version — read, never hardcoded."""
    return getattr(browserwright, "__version__", "unknown")


def _is_exception(obj: object) -> bool:
    return inspect.isclass(obj) and issubclass(obj, BaseException)


def _first_doc_line(obj: object) -> str:
    doc = inspect.getdoc(obj) or ""
    for line in doc.splitlines():
        line = line.strip()
        if line:
            return line
    return ""


def _signature(name: str, obj: object) -> str:
    try:
        return f"{name}{inspect.signature(obj)}"
    except (TypeError, ValueError):
        # builtins / C-implemented callables may have no introspectable sig
        return f"{name}(...)"


def _curated_header() -> str:
    """Return curated guidance prose, read at runtime — never frozen here.

    Preference order:
      1. ``skill_runtime.md`` shipped inside the package.
      2. The CLI ``HELP`` banner, which is itself the curated quick-start.
    """
    pkg_dir = Path(__file__).resolve().parent
    for candidate in (pkg_dir / "skill_runtime.md",):
        try:
            if candidate.is_file():
                return candidate.read_text(encoding="utf-8").rstrip()
        except OSError:
            pass
    # Fall back to the in-code curated banner so the doc is still usable.
    try:
        from .cli import HELP
        return HELP.rstrip()
    except Exception:  # noqa: BLE001
        return "browserwright — Layer 2 of the browser stack."


def _primitive_surface() -> str:
    """Render one line per callable export: signature + first docstring line.

    Enumerated from ``browserwright.EXPORTS`` so it always matches the binary.
    Exception classes in EXPORTS are listed separately (they're part of the
    surface but aren't "primitives" you call to act on the page).
    """
    funcs: list[str] = []
    errors: list[str] = []
    for name in browserwright.EXPORTS:
        obj = getattr(browserwright, name, None)
        if obj is None:
            continue
        if _is_exception(obj):
            summary = _first_doc_line(obj)
            errors.append(f"- {name}" + (f" — {summary}" if summary else ""))
            continue
        if not callable(obj):
            continue
        sig = _signature(name, obj)
        summary = _first_doc_line(obj)
        line = f"- `{sig}`"
        if summary:
            line += f" — {summary}"
        funcs.append(line)

    parts = [
        "## Primitive surface (generated from the running code)",
        "",
        f"These {len(funcs)} callables are enumerated from "
        "`browserwright.EXPORTS` at runtime, so this list always matches the "
        "inline default namespace of the installed binary.",
        "",
        *funcs,
    ]
    if errors:
        parts += [
            "",
            "### Error types",
            "",
            *errors,
        ]
    return "\n".join(parts)


def render() -> str:
    """Assemble the complete, version-locked skill document as a string."""
    version = _version()
    header = (
        f"<!-- generated by `browserwright --print-skill` — "
        f"version-locked to browserwright {version} -->\n"
        f"# browserwright {version}\n\n"
        "> This document is generated at runtime from the installed package. "
        "The version stamp and primitive surface below are emitted from the "
        "running code (`browserwright.__version__` + `browserwright.EXPORTS`), "
        "so the instructions you are reading match the binary you are running."
    )
    guidance = "## Guidance\n\n" + _curated_header()
    footer = (f"_browserwright {version} — primitive surface generated from "
              "`browserwright.EXPORTS`._")
    return "\n\n".join([
        header,
        guidance,
        _primitive_surface(),
        footer,
    ]).rstrip() + "\n"
