"""Curated unit-test collection.

The historical unit suite was pruned to this coverage-focused unit/contract set.
The hook keeps broad pytest invocations pinned to the curated list while still
allowing explicit file/nodeid runs during local development.
"""
from __future__ import annotations

import os
from pathlib import Path

_CURATED_UNIT_TESTS = {
    # Phase C PR1 foundation (facade auto-enable + lazy heredoc page/context).
    "tests/daemon/test_phase_c_foundation_unit.py::test_facade_auto_enabled_when_unset",
    "tests/daemon/test_phase_c_foundation_unit.py::test_facade_disabled_when_zero",
    "tests/daemon/test_phase_c_foundation_unit.py::test_facade_explicit_port_override",
    "tests/daemon/test_phase_c_foundation_unit.py::test_facade_port_load_default_is_none",
    "tests/daemon/test_phase_c_foundation_unit.py::test_facade_file_roundtrip",
    "tests/daemon/test_phase_c_foundation_unit.py::test_facade_file_cleanup",
    "tests/daemon/test_phase_c_foundation_unit.py::test_facade_file_bad_json",
    "tests/daemon/test_phase_c_foundation_unit.py::test_status_json_includes_facade",
    "tests/daemon/test_phase_c_foundation_unit.py::test_status_json_facade_null_when_dead",
    "tests/daemon/test_phase_c_foundation_unit.py::test_lazy_proxies_do_not_connect_on_build_globals",
    "tests/daemon/test_phase_c_foundation_unit.py::test_handle_close_is_noop_without_connect",
    "tests/daemon/test_coverage_proxy_dense.py::test_raw_frames_lifecycle_failure_and_broadcast_edges",
    "tests/daemon/test_coverage_proxy_dense.py::test_self_answer_focus_stats_version_and_backend_state",
    "tests/daemon/test_coverage_proxy_dense.py::test_extension_scoped_get_targets_success_error_and_fallback",
    "tests/daemon/test_coverage_proxy_dense.py::test_attach_response_race_variants_and_validation",
    "tests/daemon/test_coverage_proxy_dense.py::test_detach_paths_and_session_scoped_event_unbinds_readers",
    "tests/daemon/test_coverage_proxy_dense.py::test_upstream_event_table_orphan_and_pending_auto_attach_edges",
    "tests/daemon/test_coverage_proxy_dense.py::test_attach_active_extension_lazy_malformed_reuse_and_conflict",
    "tests/daemon/test_coverage_proxy_dense.py::test_open_recover_close_and_end_error_translation_branches",
    "tests/daemon/test_coverage_proxy_dense.py::test_ensure_and_end_session_daemon_edge_cases",
    "tests/daemon/test_coverage_proxy_dense.py::test_rdp_open_attach_close_error_translation_and_cleanup",
    "tests/daemon/test_coverage_proxy_dense.py::test_rdp_attach_active_reuses_local_page_and_falls_back_after_bad_targets",
    "tests/daemon/test_coverage_proxy_dense.py::test_rdp_userscript_registry_success_error_and_unsupported_paths",
    "tests/daemon/test_coverage_listener_dense.py::test_listener_query_and_process_request_cover_ping_and_windows_token",
    "tests/daemon/test_coverage_listener_dense.py::test_upstream_holder_extension_missing_relay_emits_connecting_then_fails",
    "tests/daemon/test_coverage_listener_dense.py::test_upstream_holder_open_chrome_success_wires_router_and_internal_command",
    "tests/daemon/test_coverage_listener_dense.py::test_upstream_holder_cloud_auth_success_and_user_error",
    "tests/daemon/test_coverage_listener_dense.py::test_trigger_close_sends_detach_and_closed_events_then_clears_callbacks",
    "tests/daemon/test_coverage_listener_dense.py::test_idle_watchdog_closes_idle_rdp_context_and_drops_it",
    "tests/daemon/test_coverage_listener_dense.py::test_upstream_reader_intercepts_internal_ids_forwards_binary_and_notifies_close",
    "tests/daemon/test_coverage_listener_dense.py::test_upstream_close_cancels_tasks_rejects_pending_and_resets_ws_url",
    "tests/daemon/test_coverage_listener_dense.py::test_localhost_bypass_proxy_augments_and_restores",
    "tests/daemon/test_coverage_listener_dense.py::test_relay_process_request_status_and_origin_filter",
    "tests/daemon/test_coverage_listener_dense.py::test_relay_dispatch_handles_protocol_matrix_and_pending_errors",
    "tests/daemon/test_coverage_listener_dense.py::test_relay_request_cleanup_and_public_helpers_without_socket",
    "tests/daemon/test_coverage_listener_dense.py::test_auth_and_ipc_edges_cover_url_quoting_factory_and_pid",
    "tests/skill/test_coverage_mode_b_dense.py::test_discover_normalizes_status_shapes_and_windows_port_fallback",
    "tests/skill/test_coverage_mode_b_dense.py::test_discover_ignores_bad_status_json_and_raises_on_bad_port_file",
    "tests/skill/test_coverage_mode_b_dense.py::test_ping_socket_branches_close_on_failure",
    "tests/skill/test_coverage_mode_b_dense.py::test_ws_url_caches_until_invalidated_and_carries_session_query",
    "tests/skill/test_coverage_mode_b_dense.py::test_cli_info_methods_parse_defaults_and_command_shapes",
    "tests/skill/test_coverage_mode_b_dense.py::test_cli_info_methods_tolerate_bad_outputs_and_timeouts",
    "tests/skill/test_coverage_mode_b_dense.py::test_open_background_and_close_tab_success_and_error_details",
    "tests/skill/test_coverage_mode_b_dense.py::test_doctor_returns_real_json_or_synthetic_failure",
    "tests/skill/test_coverage_mode_b_dense.py::test_ensure_version_coherent_restarts_legacy_alive_daemon_with_backend",
    "tests/skill/test_coverage_mode_b_dense.py::test_client_for_session_is_lazy_but_runs_coherence_when_alive",
    "tests/skill/test_coverage_mode_b_dense.py::test_session_resolve_retries_and_lazy_cdp_reuses_until_closed",
    "tests/skill/test_coverage_mode_b_dense.py::test_session_backend_name_caches_and_swallows_known_getter_errors",
    "tests/skill/test_coverage_mode_b_dense.py::test_resolve_session_empty_explicit_arg_refuses_even_with_env",
    "tests/skill/test_coverage_mode_b_dense.py::test_open_unix_websocket_uses_synthetic_http_upgrade",
    "tests/skill/test_coverage_mode_b_dense.py::test_cdp_send_serializes_session_returns_result_and_rewrites_stale_errors",
    "tests/daemon/test_coverage_daemon_core.py::test_cli_main_without_subcommand_prints_help",
    "tests/daemon/test_coverage_daemon_core.py::test_cli_main_maps_exceptions_to_exit_codes[exc0-130-]",
    "tests/daemon/test_coverage_daemon_core.py::test_cli_main_maps_exceptions_to_exit_codes[exc1-3-internal error: RuntimeError: surprise]",
    "tests/daemon/test_coverage_daemon_core.py::test_cli_main_unavailable_verbose_prints_attempts",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_url_mode_b_proxy_unix_text",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_url_mode_b_proxy_tcp_without_port_exits_unavailable",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_status_json_includes_dead_endpoint",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_daemon_version_check_json_reports_consistent_versions",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_active_tab_none_outputs_mode_specific_shape[False]",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_active_tab_none_outputs_mode_specific_shape[True]",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_active_tab_text_outputs_tab_separated_info",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_close_tab_requires_identifier",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_open_background_success_prints_json",
    "tests/daemon/test_coverage_daemon_core.py::test_cmd_end_session_passes_group_id",
    "tests/daemon/test_coverage_daemon_core.py::test_pretty_doctor_prints_detail_warning_and_next",
    "tests/daemon/test_coverage_daemon_core.py::test_fetch_targets_accepts_unwrapped_target_infos",
    "tests/daemon/test_coverage_daemon_core.py::test_fetch_targets_non_list_payload_returns_empty",
    "tests/daemon/test_coverage_daemon_core.py::test_fetch_targets_oserror_becomes_unavailable",
    "tests/daemon/test_coverage_daemon_core.py::test_silent_stop_swallows_client_stop_errors",
    "tests/daemon/test_coverage_daemon_core.py::test_localhost_bypass_proxy_adds_and_restores_no_proxy",
    "tests/daemon/test_coverage_daemon_core.py::test_localhost_bypass_proxy_leaves_remote_hosts_alone",
    "tests/daemon/test_coverage_daemon_core.py::test_runtime_dir_prefers_xdg",
    "tests/daemon/test_coverage_daemon_core.py::test_runtime_dir_windows_uses_tempdir",
    "tests/daemon/test_coverage_daemon_core.py::test_cache_dir_prefers_xdg_cache_home",
    "tests/daemon/test_coverage_daemon_core.py::test_chrome_binary_candidates_by_platform[Darwin-Google Chrome.app/Contents/MacOS/Google Chrome]",
    "tests/daemon/test_coverage_daemon_core.py::test_chrome_binary_candidates_by_platform[Windows-Google/Chrome/Application/chrome.exe]",
    "tests/daemon/test_coverage_daemon_core.py::test_chrome_binary_candidates_by_platform[Linux-/usr/bin/google-chrome]",
    "tests/daemon/test_coverage_daemon_core.py::test_binary_is_runnable_false_on_permission_error",
    "tests/daemon/test_coverage_daemon_core.py::test_binary_is_runnable_checks_returncode",
    "tests/daemon/test_coverage_daemon_core.py::test_proc_start_time_parses_proc_stat",
    "tests/daemon/test_coverage_daemon_core.py::test_proc_start_time_falls_back_to_ps",
    "tests/daemon/test_coverage_daemon_core.py::test_discover_chrome_binary_darwin_prefers_app_candidate_before_path",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[1-True]",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[TRUE-True]",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[yes-True]",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[on-True]",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[y-True]",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[0-False]",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[-False]",
    "tests/daemon/test_coverage_daemon_core.py::test_truthy_env_variants[no-False]",
    "tests/daemon/test_coverage_daemon_core.py::test_allocate_data_dir_persistent_uses_cache",
    "tests/daemon/test_coverage_daemon_core.py::test_spawn_kwargs_posix_starts_new_session",
    "tests/daemon/test_coverage_daemon_core.py::test_spawn_kwargs_windows_sets_creation_flags",
    "tests/daemon/test_coverage_daemon_core.py::test_silent_context_swallows_only_oserror",
    "tests/daemon/test_coverage_daemon_core.py::test_wait_for_chrome_ready_reads_devtools_active_port",
    "tests/daemon/test_coverage_daemon_core.py::test_wait_for_chrome_ready_terminates_live_process_on_timeout",
    "tests/daemon/test_coverage_daemon_core.py::test_resolver_records_unavailable_without_attempts",
    "tests/daemon/test_coverage_daemon_core.py::test_resolver_auto_chain_skips_extension_and_cloud",
    "tests/daemon/test_coverage_daemon_core.py::test_cloud_provider_is_cached",
    "tests/daemon/test_coverage_daemon_core.py::test_cloud_resolve_header_user_error_becomes_unavailable",
    "tests/daemon/test_coverage_daemon_core.py::test_cloud_resolve_http_client_error_becomes_unavailable",
    "tests/daemon/test_coverage_daemon_core.py::test_cloud_resolve_invalid_json_counts_as_missing_ws",
    "tests/daemon/test_coverage_daemon_core.py::test_userscript_payload_contains_chrome_registration_fields",
    "tests/daemon/test_coverage_daemon_core.py::test_userscript_invalid_exclude_warns_but_keeps_valid_match",
    "tests/daemon/test_coverage_daemon_core.py::test_state_bind_unbind_session_updates_lookup_tables",
    "tests/daemon/test_coverage_daemon_core.py::test_state_reader_cleanup_leaves_primary_attacher",
    "tests/daemon/test_coverage_daemon_core.py::test_state_set_disconnected_clears_upstream_tied_tables",
    "tests/daemon/test_coverage_daemon_core.py::test_state_note_target_info_ignores_non_string_target_id",
    "tests/daemon/test_coverage_daemon_core.py::test_state_note_activate_updates_activity_timestamp",
    "tests/daemon/test_coverage_daemon_core.py::test_daemon_context_for_rdp_lazily_creates_isolated_config",
    "tests/daemon/test_coverage_daemon_core.py::test_daemon_context_for_unknown_or_non_rdp_uses_shared",
    "tests/daemon/test_coverage_daemon_core.py::test_daemon_teardown_missing_rdp_context_returns_false",
    "tests/daemon/test_coverage_daemon_core.py::test_proxy_json_helpers_and_cdp_result_unwrap",
    "tests/daemon/test_coverage_daemon_core.py::test_router_release_client_detaches_only_primary_sessions",
    "tests/skill/test_coverage_cli_runtime.py::test_parse_kv_args_coerces_json_space_values_and_flags",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_version_check_json_reports_consistent_versions",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_release_status_json",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_task_rejects_bad_invocation[args0-usage: browserwright task]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_task_rejects_bad_invocation[args1-task spec must be]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_task_reports_missing_task",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_task_reports_crash",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_doctor_human_failure_prints_fixes",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_index_rejects_unknown_subcommand",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_sub_usage_errors[args0-usage: browserwright sub]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_sub_usage_errors[args1-usage: browserwright sub add]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_sub_usage_errors[args2-usage: browserwright sub remove]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_sub_usage_errors[args3-unknown sub subcommand]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_sub_surfaces_subscription_errors",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_sub_update_error_status_returns_nonzero",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_memory_usage_errors[args0-usage: browserwright memory]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_memory_usage_errors[args1-specify --site=SITE or --global]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_memory_usage_errors[args2-usage: memory forget]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_memory_usage_errors[args3-usage: memory replace]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_memory_usage_errors[args4-unknown memory subcommand]",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_memory_replace_dry_run_then_confirm",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_session_usage_errors",
    "tests/skill/test_coverage_cli_runtime.py::test_cmd_userscript_verify_skips_reload_after_push_failure",
    "tests/skill/test_coverage_cli_runtime.py::test_daemon_doctor_synthetic_for_spawn_failure",
    "tests/skill/test_coverage_cli_runtime.py::test_daemon_doctor_synthetic_for_nonzero_exit",
    "tests/skill/test_coverage_cli_runtime.py::test_daemon_doctor_synthetic_for_invalid_json",
    "tests/skill/test_coverage_cli_runtime.py::test_doctor_checks_warns_on_unknown_schema_and_fails_without_backend",
    "tests/skill/test_coverage_cli_runtime.py::test_doctor_checks_extension_unavailable_is_actionable_warn",
    "tests/skill/test_coverage_cli_runtime.py::test_session_create_run_returns_one_for_spawn_errors",
    "tests/skill/test_coverage_cli_runtime.py::test_session_create_reap_closes_only_create_owned_sessions",
    "tests/skill/test_coverage_cli_runtime.py::test_session_create_end_extension_threads_group_id",
    "tests/skill/test_coverage_cli_runtime.py::test_session_registry_unique_name_conflict_does_not_advance_ledger",
    "tests/skill/test_coverage_cli_runtime.py::test_session_registry_backend_immutability_leaves_record_unchanged",
    "tests/skill/test_coverage_cli_runtime.py::test_subscriptions_load_metadata_recovers_from_invalid_json",
    "tests/skill/test_coverage_cli_runtime.py::test_subscriptions_add_clone_failure_removes_partial_target",
    "tests/skill/test_coverage_cli_runtime.py::test_subscriptions_update_missing_subscription_is_nonfatal",
    "tests/skill/test_coverage_cli_runtime.py::test_task_runner_validate_args_defaults_and_required",
    "tests/skill/test_coverage_cli_runtime.py::test_task_runner_rejects_module_without_run",
    "tests/skill/test_coverage_cli_runtime.py::test_task_runner_uses_empty_memory_when_site_memory_read_fails",
    "tests/skill/test_coverage_cli_runtime.py::test_task_runner_isolated_session_closes_after_run",
    "tests/skill/test_coverage_cli_runtime.py::test_session_runtime_ensure_returns_existing_target_without_ledger",
    "tests/skill/test_coverage_cli_runtime.py::test_session_runtime_stale_fast_path_without_group_returns_none",
    "tests/skill/test_coverage_cli_runtime.py::test_session_runtime_register_recovered_rejects_malformed_payload",
    "tests/skill/test_coverage_cli_runtime.py::test_session_runtime_persist_target_swallows_registry_update_failure",
    "tests/skill/test_coverage_cli_runtime.py::test_session_decisions_record_creates_home_and_overwrites",
    "tests/skill/test_coverage_repl_misc.py::test_inline_run_empty_input_prints_usage",
    "tests/skill/test_coverage_repl_misc.py::test_inline_run_replays_stdout_before_browserwright_error",
    "tests/skill/test_coverage_repl_misc.py::test_inline_run_system_exit_non_integer_is_success",
    "tests/skill/test_coverage_repl_misc.py::test_inline_run_unexpected_exception_returns_traceback",
    "tests/skill/test_coverage_repl_misc.py::test_namespace_skips_same_object_shadow_without_warning",
    "tests/skill/test_coverage_repl_misc.py::test_skill_doc_falls_back_when_cli_help_import_fails",
    "tests/skill/test_coverage_repl_misc.py::test_skill_doc_signature_uses_ellipsis_for_uninspectable_callable",
    "tests/skill/test_coverage_repl_misc.py::test_discovery_iter_site_dirs_precedence_and_filters",
    "tests/skill/test_coverage_repl_misc.py::test_discovery_load_task_meta_reports_import_error",
    "tests/skill/test_coverage_repl_misc.py::test_discovery_load_site_entry_parses_skill_memory_and_task",
    "tests/skill/test_coverage_repl_misc.py::test_discovery_load_index_rebuilds_invalid_json",
    "tests/skill/test_coverage_repl_misc.py::test_output_schema_integer_rejects_bool_with_path",
    "tests/skill/test_coverage_repl_misc.py::test_output_schema_nullable_and_unknown_type_are_permissive",
    "tests/skill/test_coverage_repl_misc.py::test_output_schema_nested_array_enum_path",
    "tests/skill/test_coverage_repl_misc.py::test_errors_serialize_reprs_unjsonable_attributes",
    "tests/skill/test_coverage_repl_misc.py::test_cdp_unix_socket_adapter_ignores_tcp_options_and_delegates",
    "tests/skill/test_coverage_repl_misc.py::test_cdp_read_loop_routes_responses_and_events",
    "tests/skill/test_coverage_repl_misc.py::test_cdp_drain_events_clears_existing_buffer_and_missing_is_empty",
    "tests/skill/test_release_install.py::test_release_install_local_copies_artifacts_and_activates",
    "tests/skill/test_release_install.py::test_release_status_reports_daemon_restart_and_skill_link",
    "tests/skill/test_release_install.py::test_release_activate_rejects_missing_version",
    "tests/skill/test_release_install.py::test_version_finds_extension_manifest_from_release_parent",
    "tests/skill/test_install_cloud_v05.py::test_cloud_available_true_when_doctor_lists_it",
    "tests/skill/test_install_cloud_v05.py::test_cloud_available_false_when_entry_unavailable",
    "tests/skill/test_install_cloud_v05.py::test_cloud_available_false_when_entry_missing",
    "tests/skill/test_install_cloud_v05.py::test_menu_shows_cloud_as_coming_when_unavailable",
    "tests/skill/test_install_cloud_v05.py::test_menu_shows_cloud_as_live_when_available",
    "tests/skill/test_install_cloud_v05.py::test_choice_5_blocked_when_cloud_unavailable",
    "tests/skill/test_install_cloud_v05.py::test_wizard_choice_5_bearer_flow_writes_references",
    "tests/skill/test_install_cloud_v05.py::test_wizard_choice_5_basic_flow_writes_env_var_refs",
    "tests/skill/test_install_cloud_v05.py::test_wizard_choice_5_basic_rejects_url_with_embedded_creds",
    "tests/skill/test_install_cloud_v05.py::test_wizard_choice_5_mtls_flow_writes_cert_and_key_paths",
    "tests/skill/test_install_cloud_v05.py::test_wizard_choice_5_rejects_unknown_provider",
    "tests/skill/test_install_cloud_v05.py::test_wizard_choice_5_rejects_unknown_auth_kind",
    "tests/skill/test_install_cloud_v05.py::test_doctor_probe_is_the_only_detection_channel",
    "tests/skill/test_install_cloud_v05.py::test_live_daemon_doctor_lists_cloud_entry",
    "tests/skill/test_install_cloud_v05.py::test_live_daemon_parses_wizard_emitted_config",
    "tests/skill/test_install_cloud_v05.py::test_live_daemon_doctor_surfaces_informative_unavailability",
    "tests/skill/test_install_cloud_v05.py::test_wizard_choice_5_oauth2_rejected_as_coming_v06",
    "tests/skill/test_install_cloud_v05.py::test_wizard_prefills_from_doctor_extras",
    "tests/skill/test_install_cloud_v05.py::test_write_daemon_cloud_config_creates_subtable_layout",
    "tests/skill/test_install_cloud_v05.py::test_write_daemon_cloud_config_basic_emits_username_password_envs",
    "tests/skill/test_install_cloud_v05.py::test_write_daemon_cloud_config_mtls_uses_file_field_names",
    "tests/skill/test_install_cloud_v05.py::test_write_daemon_cloud_config_strips_stale_auth_subtables",
    "tests/skill/test_install_cloud_v05.py::test_write_daemon_cloud_config_preserves_other_sections",
    "tests/skill/test_install_extension_v04.py::test_extension_available_true_when_doctor_reports_available",
    "tests/skill/test_install_extension_v04.py::test_extension_available_false_when_entry_unavailable",
    "tests/skill/test_install_extension_v04.py::test_extension_available_false_when_entry_missing",
    "tests/skill/test_install_extension_v04.py::test_extension_available_false_when_doctor_synthetic_error",
    "tests/skill/test_install_extension_v04.py::test_chrome_extension_path_env_override",
    "tests/skill/test_install_extension_v04.py::test_chrome_extension_path_daemon_subprocess_json",
    "tests/skill/test_install_extension_v04.py::test_chrome_extension_path_returns_none_when_daemon_missing",
    "tests/skill/test_install_extension_v04.py::test_wizard_choice_4_available_writes_preference",
    "tests/skill/test_install_extension_v04.py::test_wizard_choice_4_unavailable_blocks",
    "tests/skill/test_install_extension_v04.py::test_wizard_choice_4_available_no_path_falls_back_to_hint",
    "tests/skill/test_install_extension_v04.py::test_wizard_extension_option_renders_as_coming_when_unavailable",
    "tests/skill/test_install_extension_v04.py::test_wizard_extension_option_renders_live_when_available",
    "tests/daemon/test_extension_upstream.py::test_tab_id_extraction_helpers",
    "tests/daemon/test_extension_upstream.py::test_target_get_targets_returns_ghosts_from_relay",
    "tests/daemon/test_extension_upstream.py::test_target_attach_via_extension_returns_synthetic_session_id",
    "tests/daemon/test_extension_upstream.py::test_target_attach_unknown_target_id_returns_invalid_params",
    "tests/daemon/test_extension_upstream.py::test_browser_crash_returns_method_not_found",
    "tests/daemon/test_extension_upstream.py::test_target_set_discover_targets_is_silent_ack",
    "tests/daemon/test_extension_upstream.py::test_session_scoped_command_forwarded_via_relay",
    "tests/daemon/test_extension_upstream.py::test_session_scoped_command_with_unknown_session_id_errors",
    "tests/daemon/test_extension_upstream.py::test_attach_active_tab_returns_fabricated_session_id",
    "tests/daemon/test_extension_upstream.py::test_extension_event_translated_to_cdp_frame_with_session_id",
    "tests/daemon/test_extension_upstream.py::test_open_background_tab_returns_fabricated_session",
    "tests/daemon/test_extension_upstream.py::test_close_tab_removes_session",
    "tests/daemon/test_extension_upstream.py::test_close_tab_unknown_session_raises_value_error",
    "tests/daemon/test_extension_upstream.py::test_sessions_bind_distinct_groups",
    "tests/daemon/test_extension_upstream.py::test_open_background_passes_bound_group_id",
    "tests/daemon/test_extension_upstream.py::test_attach_active_adopts_into_group",
    "tests/daemon/test_extension_upstream.py::test_attach_active_passes_bound_group",
    "tests/daemon/test_extension_upstream.py::test_end_session_closes_whole_group",
    "tests/daemon/test_extension_upstream.py::test_recover_session_reattaches_tabs_and_rebuilds_state",
    "tests/daemon/test_extension_upstream.py::test_recover_session_empty_group_raises",
    "tests/daemon/test_extension_upstream.py::test_end_session_resolves_group_by_passed_id_when_unbound",
    "tests/daemon/test_extension_upstream.py::test_session_info_live_fields",
    "tests/daemon/test_extension_upstream.py::test_list_tabs_resolves_from_live_group_membership",
    "tests/daemon/test_extension_upstream.py::test_scoped_target_infos_filters_ghosts_to_session_group",
    "tests/daemon/test_doctor.py::test_doctor_schema_v1_top_shape",
    "tests/daemon/test_doctor.py::test_doctor_every_backend_has_full_key_set",
    "tests/daemon/test_doctor.py::test_doctor_recommended_picks_lowest_ux_cost",
    "tests/daemon/test_doctor.py::test_doctor_recommended_none_when_nothing_available",
    "tests/daemon/test_doctor.py::test_doctor_default_opens_no_ws",
    "tests/daemon/test_doctor.py::test_doctor_probe_ws_flag_explicitly_rejects_in_v01",
    "tests/daemon/test_doctor.py::test_doctor_backend_filter_keeps_full_shape",
    "tests/daemon/test_doctor.py::test_recommended_picks_extension_when_only_one_available",
    "tests/daemon/test_doctor.py::test_recommended_rdp_still_beats_extension_on_ux_cost",
    "tests/daemon/test_doctor.py::test_needs_action_extension_hint_no_longer_says_planned_v04",
    "tests/daemon/test_doctor.py::test_needs_action_cloud_row_exists",
    "tests/daemon/test_doctor.py::test_needs_action_unknown_backend_still_none",
    "tests/daemon/test_auth.py::test_bearer_explicit_token_emits_authorization_header",
    "tests/daemon/test_auth.py::test_bearer_token_env_reads_environment",
    "tests/daemon/test_auth.py::test_bearer_missing_env_raises_user_error",
    "tests/daemon/test_auth.py::test_bearer_neither_token_nor_env_raises",
    "tests/daemon/test_auth.py::test_bearer_custom_header_name_and_prefix",
    "tests/daemon/test_auth.py::test_basic_default_header_mode_emits_b64_authorization",
    "tests/daemon/test_auth.py::test_basic_url_embed_via_url_with_auth_mode_a_path",
    "tests/daemon/test_auth.py::test_basic_url_with_auth_preserves_existing_creds",
    "tests/daemon/test_auth.py::test_basic_embed_in_url_flag_no_header",
    "tests/daemon/test_auth.py::test_basic_env_resolution",
    "tests/daemon/test_auth.py::test_basic_missing_creds_raises",
    "tests/daemon/test_auth.py::test_mtls_loads_client_cert_chain_into_ssl_context",
    "tests/daemon/test_auth.py::test_mtls_headers_empty_url_unchanged",
    "tests/daemon/test_auth.py::test_mtls_missing_files_raise_user_error",
    "tests/daemon/test_auth.py::test_mtls_requires_cert_and_key_paths",
    "tests/daemon/test_auth.py::test_oauth2_stub_raises_user_error_everywhere",
    "tests/daemon/test_auth.py::test_factory_builds_bearer",
    "tests/daemon/test_auth.py::test_factory_builds_basic_with_embed_flag",
    "tests/daemon/test_auth.py::test_factory_builds_mtls",
    "tests/daemon/test_auth.py::test_factory_builds_oauth2_stub",
    "tests/daemon/test_auth.py::test_factory_unknown_kind_raises",
    "tests/daemon/test_auth.py::test_concrete_providers_satisfy_auth_provider_protocol",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_end_to_end",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_binary_not_found_raises",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_invalid_profile_name_raises",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_falls_back_to_json_version_when_devtools_port_missing",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_no_fallback_without_explicit_port",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_devtools_port_never_appears_raises",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_passes_remote_allow_origins_flag",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_keeps_polling_when_launcher_proc_exits",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_dying_chrome_error_includes_exit_code",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_refuses_user_default_profile",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_isolated_profile_passes_guard",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_allow_default_profile_flag_unlocks",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_env_var_unlocks_default_profile_guard",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_passes_extra_args",
    "tests/daemon/test_launch_chrome.py::test_discover_chrome_binary_skips_wrapper_that_exits_nonzero",
    "tests/daemon/test_launch_chrome.py::test_discover_chrome_binary_explicit_path_validates_too",
    "tests/daemon/test_launch_chrome.py::test_discover_chrome_binary_accepts_working_explicit_path",
    "tests/daemon/test_launch_chrome.py::test_discover_chrome_binary_returns_none_when_nothing_works",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_refuses_default_profile_via_symlink",
    "tests/daemon/test_launch_chrome.py::test_launch_chrome_yes_env_unlocks_default_profile_guard",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_main_parses_config_and_dispatches_core_commands",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_offline_static_handlers_cover_output_modes",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_status_list_and_stop_error_branches",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_backend_info_stats_attach_and_rpc_success_paths",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_rpc_disconnect_attach_error_paths",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_userscript_actions_success_and_error_sweep",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_userscript_install_stdin_failed_sync_warns",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_tab_rpc_handlers_cover_success_and_failures",
    "tests/daemon/test_coverage_daemon_cli_sweep.py::test_launchagent_install_uninstall_and_launchctl_sweep",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_process_request_ping_windows_token_and_origin",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_open_server_windows_and_unix_bind_branches",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_run_serve_existing_pid_and_extension_relay_bind_failure",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_client_handler_routes_session_frames_and_releases",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_extension_upstream_success_wires_callbacks_and_ready_events",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_rdp_launch_kill_and_upstream_closed_drop_context",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_graceful_shutdown_closes_every_context_despite_errors",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_upstream_open_passes_headers_ssl_and_heartbeat_failure",
    "tests/daemon/test_coverage_server_listener_sweep.py::test_upstream_reader_handles_bad_frames_callback_errors_and_close_callback_errors",
    "tests/skill/test_coverage_primitives_sweep.py::test_interact_js_error_and_serialization_paths",
    "tests/skill/test_coverage_primitives_sweep.py::test_interact_input_fill_click_upload_and_dispatch_paths",
    "tests/skill/test_coverage_primitives_sweep.py::test_interact_waits_and_network_idle_cover_errors_and_timeout",
    "tests/skill/test_coverage_primitives_sweep.py::test_page_open_current_goto_reload_close_error_sweep",
    "tests/skill/test_coverage_primitives_sweep.py::test_page_success_paths_current_goto_reload_and_close_cleanup",
    "tests/skill/test_coverage_primitives_sweep.py::test_http_get_fetch_fallback_gzip_and_headers",
    "tests/skill/test_coverage_primitives_sweep.py::test_site_memory_host_resolution_confirm_and_reads",
    "tests/skill/test_coverage_primitives_sweep.py::test_cdp_send_attach_detach_readonly_close_and_read_loop",
    "tests/skill/test_coverage_primitives.py::test_capture_screenshot_annotates_writes_and_always_clears",
}

_GENERIC_TEST_ARGS = {"tests", "tests/", "tests/daemon", "tests/daemon/", "tests/skill", "tests/skill/"}


def _explicit_target_requested(config) -> bool:
    for arg in config.args:
        normalized = arg.replace("\\", "/")
        if "tests/daemon/e2e" in normalized or "::" in normalized:
            return True
        if normalized.endswith(".py"):
            return True
        if normalized not in _GENERIC_TEST_ARGS:
            return True
    return False


def pytest_collection_modifyitems(config, items):
    if os.environ.get("BROWSERWRIGHT_FULL_UNIT") == "1":
        return
    if "real_chrome" in (config.getoption("-m", default="") or ""):
        return
    if _explicit_target_requested(config):
        return

    selected = []
    deselected = []
    root = Path(str(config.rootpath))
    for item in items:
        try:
            rel = item.path.relative_to(root).as_posix()
        except ValueError:
            rel = item.path.as_posix()
        nodeid = f"{rel}::{item.name}"
        if nodeid in _CURATED_UNIT_TESTS:
            selected.append(item)
        else:
            deselected.append(item)

    if deselected:
        config.hook.pytest_deselected(items=deselected)
        items[:] = selected
